const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let signup=false,tasks=[],resources=[],me=null;
const subjects=[["Data Structures","BCS-301","#5961d7"],["Operating Systems","BCS-302","#df6c46"],["Python Programming","BCC-301","#299574"],["Mathematics III","BAS-303","#b768ad"]];
async function api(url,options={}){const r=await fetch(url,options);let body={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.error||"Request failed");return body}
function toast(message){const t=$("#toast");t.textContent=message;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2400)}
function showAuth(){$("#auth").classList.remove("hidden");$("#app").classList.add("hidden")}
async function boot(){try{me=await api("/api/me");$("#auth").classList.add("hidden");$("#app").classList.remove("hidden");const first=me.name.split(" ")[0],initials=me.name.split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase();$("#userName").textContent=first;$("#firstName").textContent=first;$("#initials").textContent=initials;$("#topInitials").textContent=initials;$("#subjects").innerHTML=subjects.map(s=>`<article class="subject" style="--c:${s[2]}"><small>${s[1]}</small><b>${s[0]}</b></article>`).join("");await refresh()}catch{showAuth()}}
async function refresh(){[tasks,resources]=await Promise.all([api("/api/tasks"),api("/api/resources")]);render()}
function taskHtml(t){return `<article class="task ${t.completed?"done":""}"><button class="check" data-check="${t.id}">${t.completed?"✓":""}</button><div><b>${esc(t.title)}</b><small>${esc(t.subject)}</small></div><span class="pill">${esc(t.priority)}</span><time>${t.dueDate?new Date(t.dueDate+"T00:00:00").toLocaleDateString("en-IN",{day:"numeric",month:"short"}):"No deadline"}</time></article>`}
function resourceHtml(r){return `<article class="resource"><span>📄</span><div><b>${esc(r.title)}</b><small>${esc(r.subject)} · ${esc(r.filename)} · by ${esc(r.uploader)}</small></div><span class="pill">${esc(r.category)}</span><a href="/api/resources/${r.id}/download">Download</a></article>`}
function render(){const pending=tasks.filter(t=>!t.completed);$("#taskCount").textContent=pending.length;$("#resourceCount").textContent=resources.length;$("#homeTasks").innerHTML=pending.length?pending.slice(0,5).map(taskHtml).join(""):'<div class="empty">You’re all caught up. Add faculty work here.</div>';$("#tasks").innerHTML=tasks.length?tasks.map(taskHtml).join(""):'<div class="empty">No tasks yet. Add your first private task.</div>';filterResources()}
function filterResources(){const q=$("#search").value.toLowerCase();const list=resources.filter(r=>(r.title+" "+r.subject+" "+r.category).toLowerCase().includes(q));$("#resources").innerHTML=list.length?list.map(resourceHtml).join(""):'<div class="empty">No shared resources found.</div>'}
function esc(v){const d=document.createElement("div");d.textContent=v;return d.innerHTML}
$("#authSwitch").onclick=()=>{signup=!signup;$$(".signup-only").forEach(e=>e.style.display=signup?"grid":"none");$("#authTitle").textContent=signup?"Join StudyNest":"Welcome back";$("#authCopy").textContent=signup?"Use the invite code shared by your friend.":"Sign in to your StudyNest workspace.";$("#authSwitch").textContent=signup?"Already have an account? Sign in":"New here? Create an account";$("#authForm button").textContent=signup?"Create account":"Sign in"};
$$(".signup-only").forEach(e=>e.style.display="none");
$("#authForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),data=Object.fromEntries(f);try{await api(signup?"/api/auth/signup":"/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});e.target.reset();await boot()}catch(err){toast(err.message)}};
$("#logout").onclick=async()=>{await api("/api/auth/logout",{method:"POST"});showAuth()};
$$(".nav").forEach(b=>b.onclick=()=>{$$(".nav").forEach(x=>x.classList.remove("active"));b.classList.add("active");$$(".view").forEach(v=>v.classList.add("hidden"));$("#"+b.dataset.view+"View").classList.remove("hidden");$("aside").classList.remove("open")});
$("#menu").onclick=()=>$("aside").classList.toggle("open");
$("#search").oninput=filterResources;
$$("[data-modal]").forEach(b=>b.onclick=()=>$("#"+b.dataset.modal+"Modal").showModal());
$$("dialog .close").forEach(b=>b.onclick=()=>b.closest("dialog").close());
$("#taskForm").onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));try{await api("/api/tasks",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});e.target.reset();$("#taskModal").close();toast("Private task added");await refresh()}catch(err){toast(err.message)}};
$("#uploadForm").onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector("button");button.disabled=true;button.textContent="Uploading…";try{await api("/api/resources",{method:"POST",body:new FormData(e.target)});e.target.reset();$("#uploadModal").close();toast("File shared with your circle");await refresh()}catch(err){toast(err.message)}finally{button.disabled=false;button.textContent="Upload to circle"}};
document.addEventListener("click",async e=>{const b=e.target.closest("[data-check]");if(!b)return;const task=tasks.find(t=>t.id===Number(b.dataset.check));await api("/api/tasks/"+task.id,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({completed:!task.completed})});await refresh()});
boot();
